### ISSUE TITLE
Invalid destination platform sdk/name

### ISSUE THREAD

**Issue by damavik** [paypal/paypal-here-sdk-ios-distribution#106]
**iphonesimulator** is pointed both for destination platform sdk and name:
https://github.com/PayPal-Mobile/ios-here-sdk-dist/blob/master/SDK/Release/PayPalHereSDK.bundle/Info.plist 

That's incorrect. Should be **iphoneos**

**Comment by ppmtscory** [comment]
Thank you for bringing this to our attention.  I'll have the guys fix this with the next release.

**Comment by damavik** [comment]
Thanks a lot!

**Comment by damavik** [comment]
@ppmtscory Hi! Any estimates regarding next release? Seems like a bunch of fixes (especially for a sandbox mode) should have been implemented.

**Comment by ppmtscory** [comment]
@damavik I'm not very confident that there will be another release for this SDK unless there is something breaking that needs to have an urgent fix.  We're all hands on deck currently with trying to release our new SDK (2.0) to the public so that will likely be the next thing pushed for iOS, Android, and Windows.  Timing is TBD yet but very hopeful it will be before the end of this year.

**Comment by ppmtscory** [comment]
The new SDK (v2) has been published and is now available.
