### ISSUE TITLE
PayPal HERE SDK URI

### ISSUE THREAD

**Issue by kevintparker** [paypal/paypal-here-sdk-ios-distribution#109]
PayPal Technical support forwarded me so I was hoping someone can give me an answer here. I am posting this on both Android and Apple PayPal SDK sites. 

**_Based on the documentation:
The PayPal Here SDK for iOS is a collection of classes, protocols, and other resources for developing point-of-sale apps that run in iOS. It communicates with the underlying PayPal APIs at the following URIs:
https://www.paypal.com/webapps/hereapi/merchant/v1               Live environment_**

A simple GET to this (properly passing oAuth access token)
https://www.paypal.com/webapps/hereapi/merchant/v1/invoices

returns the top 50 invoices and also a hasMoreResults set to false.

I assume that I can somehow get more than 50 results using some sort of filter. 

I have tried to POST using json, x-www-form-urlencoded, I have tried adding URL variables, nothing works. I get 400 Bad Request.

**How can I filter to get more than 50?**

The developer documentation which is linked below gives a 404 error:
https://github.com/paypal/paypal-here-sdk-ios-distribution/blob/master/docs/DeveloperGuide_iOS.pdf

**Comment by ppmtscory** [comment]
What you get with that call is what you'll get.  Can you outline what you want to do exactly and I can recommend the right way of doing it?  For what you want to do, whether it be list or search, you can utilize the REST Invoicing APIs accordingly.

**Comment by kevintparker** [comment]
I am trying to create a online report.

I wrote a web application that uses the sideloader perfectly. We store the invoice and our 'order id' in a flat file json database (firebase to be exact) just before creating the invoice and sending to the PayPal HERE app. 

The PayPal Invoicing API worked for all transactions except Cash and Check, so after scouring the internet, I found the hereapi URI mentioned in the SDK for iOS and Andriod. That worked for us until we had more that 50 transactions and our reports were wrong.

The report takes the json we saved before going to the PayPal HERE app, and the actual transactions processed (need to eliminate cancelled/declined transactions) and joins the values based on our unique order id. We can then create the orders for the products, and receipt transactions in our system accordingly.

**Comment by ppmtscory** [comment]
Well, there's a couple of options you can play with.  You can get a [List of Invoices](https://developer.paypal.com/docs/api/invoicing/#invoices_get-all) and adjust the `page_size` accordingly.  Otherwise, you can use the [Invoice Search](https://developer.paypal.com/docs/api/invoicing/#invoices_search) and then you can search based off of the `number` field to match up with your own order ID you sent in.  

In either scenario, make sure to add an additional header in your call - `X-PAYPAL-REQUEST-SOURCE: MPA-DEVICE`.  You'll need to be sure to pass this so that it will _only_ grab the PPH invoices and not any other invoices that may have been created via API or through the account.

**Comment by kevintparker** [comment]
Your last paragraph was what I have been searching the entire internet for. I think I can even update my Stackoverflow question from a couple of weeks ago in which I thought the hereapi URI would work.

Thank you.
