### ISSUE TITLE
Please Remove Card modal not dismissing

### ISSUE THREAD

**Issue by joeynelson42** [paypal/paypal-here-sdk-ios-distribution#131]
When using processPaymentUsingUI a transaction with a chip reader in swift, the next screen that shows up is frozen and doesn't allow me to do anything.  I am returning the correct navigation controller and everything.  Is there a solution for this? 
![img_0355](https://user-images.githubusercontent.com/10519018/27357174-68313650-55ce-11e7-864a-43ee2c48ce36.PNG)

**Comment by jnwagstaff** [comment]
I have the same problem when trying to call processPaymentUsingUI within a swift file.

**Comment by joeynelson42** [comment]
I think #3 might be our issue, we have a somewhat complex UI structure. I'll let you know how things go!
Thanks!

**Comment by jnwagstaff** [comment]
So before I had a tab bar hidden in my app and even when not hiding it I am getting the same problem.  Is there any way you could send me your swift sample app?  Whenever a signature is required it shows the signature view with the modal already on top of it and you can't navigate anywhere with it.

**Comment by jnwagstaff** [comment]
Also this only happens when a signature is required could I be missing another element for that?

**Comment by ppmtscory** [comment]
As long as the SDK UI is being presented from the top view of your hierarchy, with nothing else in the way, it should be fine.  I can share my very simple sample, sure, but I need to clean it up first because there's a done of random commented code.  I'll see if I can get some time to do that today sometime.

**Comment by ppmtscory** [comment]
Attached is a zip of my very simple sample app.  It was an app put together through an online Swift course and not all of the functionality of the app itself works (the pictures don't xfer in the segue because I broke it somehow) but the PayPal Here portion definitely works just fine.  Also, don't make fun of my coding skills - I'm a rookie yet. :)

The merchant loads on the first page, invoice is created when the second page loads, and you click the Buy Now link at the bottom of the second page to activate the reader to show payment options.

[Algorhythm.zip](https://github.com/paypal/paypal-here-sdk-ios-distribution/files/1095654/Algorhythm.zip)

**Comment by jnwagstaff** [comment]
Thanks so much! I was able to solve my problem

**Comment by ppmtscory** [comment]
Thanks for the update @jnwagstaff.

@joeynelson42 were you able to get your UI all configured correctly?

**Comment by joeynelson42** [comment]
I did! Thanks @ppmtscory!
