### ISSUE TITLE
SDK not auto-refreshing token on expiry

### ISSUE THREAD

**Issue by thwaiteschris** [paypal/paypal-here-sdk-ios-distribution#135]
I have implemented my own OAuth server. The user can log on to get their composite token as expected.

However, when that token expires, the iOS PayPalHere SDK does not seem to be able to refresh it.

For info, I am running setupWithCompositeTokenString

with the the long composite token that works for the first 8 hours, so the format, encoding, etc must be correct:
`"live:WyJBMjNBQUVEd2......ZSE9QTTM1UHVaRy0xeGZSWV9sZXppRVp1ZyJd"
`
The encoded part decodes as something like this:
`["A23AAEDw......LGWFOBhOad9BJFEfiK9gPQ",28800,"https://XXXadmin.co.uk/PayPal/RefreshToken?refreshToken=R23AAGrSpFPm...........sYKP58AnwYNMaHrbCDk3YHOPM35PuZG-1xfRY_leziEZug"]`

When I try to use this token, I get the following message in the response.error of the setupWithCompositeTokenString callback:

> The provided access token is no longer valid. It may have simply expired; if so, you should use your refresh token to request a new access token. If this fails, your access to this API has been revoked.

If I look at my OAuth server logs, I can see that the SDK did indeed make a call to the correct refresh URL.
That refresh URL simply returns a json string without any markup:

`{"token_type":"Bearer","expires_in":"28800","access_token":"A23AAGyl........rvKIniPtbzWQ"} `

So, for some reason this returned access_token is not being picked up by the SDK. When I use this access token to manually create my own composite string, then that string DOES allow the app to connect.

So I guess what I'm asking is:
1) Does the above json string returned by the refresh URL look OK to you?
2) Should the json string be returned with any special/significant headers?
3) Is there any way to debug further into this, so I can work out what's going on? If it's useful I can send the whole of the xcode output log, although I can't see anything significant in there.

Thanks.

**Comment by ppmtscory** [comment]
Did you deploy our Node sample server that we have or are you doing this on your own?  I'm not seeing any issues currently with my deployment of the sample server but I'll check again tomorrow when the first access token expires to see if it will auto refresh like it should.

**Comment by thwaiteschris** [comment]
Thanks for responding. 

I've written my own simple OAuth server in c# to run on our IIS web server.

I used this link (from the http://pp-retail.com/sdk/ step 4 - Granting Merchant Permissions page):

> https://github.com/rypay191/OAuth2_PHP_Simple_Retail_Sample


There's at least one issue with this code. When getting the access token from the refresh token, it re-sets the scope. This broke the new access token. Removing the scope parameter when making the call to refresh the access token meant that I ended up with a working access token from my refresh call.

But the fact that it didn't work in the original code makes me wonder whether there's something else missing too. Does the output from my refresh URL look like you think it should?

It's this:

> {"token_type":"Bearer","expires_in":"28800","access_token":"A23AAGyl........rvKIniPtbzWQ"}

But for some reason the SDK doesn't seem to be able to correctly read the json that my refresh URL emits. Which is why I was wondering if it's a header issue, or something like that.

This is in a live environment so I don't really want to hand out my composite token here, but I'd be happy to send it in a pm or email, if that would help.

**Comment by ppmtscory** [comment]
@thwaiteschris I may have found an issue in our refresh logic of the SDK that's causing the issue.  This failure to retry on a certain internal endpoint is causing the issue you are seeing as it’s not being retried with the refreshed access token.  The bad news is that our resources are all tied up with higher priority things regarding our new SDK that we’re trying to release.  With that being said, you will need to implement a workaround so that you don’t have to rely on the SDK’s refresh URL logic.

This workaround would be to implement a timer on your end that would automatically reach out to your server and refresh the access token prior to expiration.  Most folks that have implemented this have set the timer for around 7 hours since the access token is good for 8 hours.  What you would do is have your app reach out to your server, refresh the access token, and then pass that back into the SDK to run the ‘setupWithCredentials’ call to re-initialize the merchant.

**Comment by thwaiteschris** [comment]
OK, thanks for letting me know and putting me out of my misery!

I'll implement a workaround of some sort.
