### ISSUE TITLE
tc!.setCompletedHandler never called

### ISSUE THREAD

**Issue by civocr** [paypal/paypal-here-sdk-ios-distribution#183]
Hi 

I'm testing payments within the Sample app, but whether the payment is successful or declined the completedhandler is never called.

Am I missing something?

**Comment by ppmtscory** [comment]
When are you expecting it?  You won't see the completionHandler being called until after the dismissal of the receipt options screen.

**Comment by civocr** [comment]
I sorted it out, turns out the remote call to refresh token to my own server was causing an issue with the card reader reporting back that the payment was declined.

Is there any way to stop the app from showing the payment complete/declined send receipt screen? Only because we handle this process internally and its 1 extra step for my operators to press cancel

**Comment by ppmtscory** [comment]
At this time, there is not a way to remove that receipt options screen, no.  We're working on enhancements for future releases and this is one of them.  We'd provide a Receipt API so that you can get the certified EMV data to port over to your receipt.  I will mark this issue as an enhancement and report back when this feature is available publicly.
