### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference

### ISSUE THREAD

**Issue by anton8900** [paypal/paypal-here-sdk-ios-distribution#286]
Can you fix that NPE?

java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null
at com.paypal.paypalretailsdk.ui.scan.ScanReadersPresenter.onDestroy (ScanReadersPresenter.java:173)
at com.paypal.paypalretailsdk.ui.DeviceConnectionActivity.onResume (DeviceConnectionActivity.java:103)

**Comment by DJ92** [comment]
Hey @anton8900 ,

Firstly, these are android issues and I'd appreciate if you can comment on the android git repo. Also, the NPE's are caused because the callback needs to be handled inside the `runOnUIThread()` method since the SDK is asynchronous. If you can share a snippet, I can take a closer look as well.

Thanks!

**Comment by DJ92** [comment]
Closing on the iOS thread for now. Please send me your collective queries/responses on my email.
